import { dataWikiShape } from "../types/data/dataWikiInterface";

export const dataWiki: dataWikiShape[] = [
  {
    id: "O1",
    photo: "./components/imageWiki/ourflag/stede.png",
    nCharacter: "Stede Bonnet",
    actor: "Rhys Darby",
    description: "string",
    status: "Alive",
    gender: "Male",
    age: "30 aprox.",
    affilation: "Revenge",
    episode: "Pilot",
  },
  {
    id: "O2",
    photo: "./components/imageWiki/ourflag/ed.png",
    nCharacter: "Edward 'Ed' Teach",
    actor: "Taika Waititi",
    description: "string",
    status: "Alive",
    gender: "Male",
    age: "35 - 40 aprox.",
    affilation: "string",
    episode: "A Gentleman Pirate",
  },
  {
    id: "O3",
    photo: "./components/imageWiki/ourflag/lucius.png",
    nCharacter: "Lucius Spriggs",
    actor: "Nathan Foad",
    description: "string",
    status: "Unknow",
    gender: "Male",
    age: "Unknow",
    affilation: "Revenge",
    episode: "Pilot",
  },
  {
    id: "O4",
    photo: "./components/imageWiki/ourflag/olu.pngg",
    nCharacter: "Oluwande Boodhari",
    actor: "Samson Kayo",
    description: "string",
    status: "Alive",
    gender: "Male",
    age: "Unknow",
    affilation: "Revenge",
    episode: "Pilot",
  },
];
